Fix bug check wrong version React 16.12.0
This condition cause crash my app.
react-barcode.js:18 Uncaught TypeError: ref.getDOMNode is not a function